sonar.projectKey=diegomad14_gcp-engineering-platform-api
sonar.organization=diegomad14
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
