"""Service Factory — generates onboarding artifacts for new services.

Generates YAML contracts, caller workflow files, and checklists.
Does NOT create GCP resources, IAM bindings, or secrets.
"""

import textwrap
import json
from pathlib import Path

from ..models import ServiceFactoryPlan, ServiceFactoryRequest, ServiceFactoryTemplate

_KNOWN_TEMPLATES = [
    ServiceFactoryTemplate(
        name="cloud-run-api",
        description="Cloud Run API service (Python FastAPI)",
        type="api",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-web",
        description="Cloud Run Web service (React/Vite/nginx)",
        type="web",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-worker",
        description="Cloud Run worker service (background processing)",
        type="worker",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-integration",
        description="Cloud Run integration adapter (external API proxy)",
        type="integration",
    ),
]

_REPO_ROOT = Path(__file__).resolve().parents[3]
_TEMPLATE_DIR = _REPO_ROOT / "templates" / "github-actions"


def _build_yaml_contract(req: ServiceFactoryRequest) -> str:
    """Generate the gcp-service-release.yaml contract."""
    return textwrap.dedent(
        f"""\
    # Service release contract — generated by Engineering Platform Service Factory
    # Repo: {req.repository}

    service:
      name: {req.service_name}
      repository: {req.repository}
      type: {req.service_type}

    release_target:
      platform: gcp-cloud-run
      service_name: {req.service_name}
      project_id: {req.gcp_project}
      region: {req.region}
      url: https://{req.service_name}-XXXXX-uc.a.run.app
      health_path: {req.health_path}
      openapi_path: {req.openapi_path}
      expected_openapi_paths: 1

    validation_targets:
      smoke_endpoints:{_format_validation_targets(req.validation_targets)}

    quality:
      quality_gate:
        enabled: true
        profile: {req.quality_profile or req.runtime}
        working_directory: {req.quality_working_directory}
        coverage_threshold: {req.coverage_threshold}
        policy_version: oss-v2
        differential_threshold: 80
        blocking: true

    security:
      workload_identity_provider: ${{{{ vars.GCP_WIF_PROVIDER }}}}
      deployer_service_account: ${{{{ vars.GCP_WIF_SERVICE_ACCOUNT }}}}
      forbidden:
        - GCP_SA_KEY
        - service_account_json
        - .env

    finops:
      labels:
        service: {req.service_name}
        env: {req.environment}
        owner: {req.owner}
        cost_center: {req.cost_center}
    """.replace("${{{{", "${{")
    )


def _format_validation_targets(targets: list[str]) -> str:
    if not targets:
        return " []"
    lines = []
    for t in targets:
        lines.append(f"      - name: {t}")
        lines.append("        path: /health")
        lines.append("        expected_status: 200")
        lines.append("        pii_safe: true")
        lines.append("        external_source: true")
    return "\n" + "\n".join(lines)


def _build_caller_workflow(
    workflow_name: str,
    platform_workflow: str,
    service_name: str,
    service_type: str,
    quality_profile: str,
    quality_working_directory: str,
    coverage_threshold: float,
) -> str:
    """Generate a caller workflow YAML."""
    if platform_workflow == "reusable-pr-check.yml":
        return textwrap.dedent(
            f"""\
        # {workflow_name} — generated by Engineering Platform Service Factory
        name: {workflow_name}

        on:
          pull_request:
            branches: [main]
          push:
            branches: [main]

        permissions:
          contents: read

        jobs:
          quality:
            uses: diegomad14/gcp-engineering-platform-api/.github/workflows/reusable-quality-gate.yml@b6455d24611ee244414de66abe63e5507d2398a8
            with:
              service-name: {service_name}
              profile: {quality_profile}
              working-directory: {quality_working_directory}
              coverage-threshold: {coverage_threshold}
              platform-ref: b6455d24611ee244414de66abe63e5507d2398a8
              platform-api-url: ${{{{ vars.ENG_PLATFORM_API_URL }}}}
            secrets:
              QUALITY_API_TOKEN: ${{{{ secrets.QUALITY_API_TOKEN }}}}
        """.replace("${{{{", "${{")
        )

    dispatch = "workflow_dispatch:"
    quality_sha_value = "${{ github.sha }}"
    runner_label_value = "${{ vars.CGM_ACTIONS_RUNNER }}"
    if platform_workflow in {
        "reusable-cloud-run-promote.yml",
        "reusable-cloud-run-rollback.yml",
    }:
        dispatch = textwrap.dedent("""\
        workflow_dispatch:
          inputs:
            quality_commit_sha:
              description: Commit SHA approved by the quality gate
              required: true
              type: string
            runner_label:
              description: Emergency runner label; leave empty for hosted runner
              required: false
              default: ""
              type: string
        """).rstrip()
        quality_sha_value = "${{ inputs.quality_commit_sha }}"
        runner_label_value = "${{ inputs.runner_label }}"
    header = textwrap.dedent(f"""\
    # {workflow_name} — generated by Engineering Platform Service Factory
    # Calls: diegomad14/gcp-engineering-platform-api/.github/workflows/{platform_workflow}

    name: {workflow_name}

    on:
    """)
    body = textwrap.dedent(
        f"""\
    permissions:
      contents: read
      id-token: write

    jobs:
      call:
        uses: diegomad14/gcp-engineering-platform-api/.github/workflows/{platform_workflow}@b6455d24611ee244414de66abe63e5507d2398a8
        with:
          project-id: ${{{{ vars.GCP_PROJECT_ID }}}}
          region: ${{{{ vars.GCP_REGION }}}}
          workload-identity-provider: ${{{{ vars.GCP_WIF_PROVIDER }}}}
          deployer-service-account: ${{{{ vars.GCP_WIF_SERVICE_ACCOUNT }}}}
          api-service-name: {service_name}
          platform-api-url: ${{{{ vars.ENG_PLATFORM_API_URL }}}}
          quality-gate-enabled: true
          quality-commit-sha: {quality_sha_value.replace("${{", "${{{{")}
          runner_label: {runner_label_value.replace("${{", "${{{{")}
        secrets:
          QUALITY_API_TOKEN: ${{{{ secrets.QUALITY_API_TOKEN }}}}
    """.replace("${{{{", "${{")
    )
    return header + textwrap.indent(dispatch, "  ") + "\n\n" + body


def _build_quality_config(req: ServiceFactoryRequest) -> str:
    """Generate the repository-owned quality gate configuration."""
    return textwrap.dedent(f"""\
    # Open source quality gate — consumed by reusable-quality-gate.yml
    service_name: {req.service_name}
    profile: {req.quality_profile or req.runtime}
    working_directory: {req.quality_working_directory}
    coverage_threshold: {req.coverage_threshold}
    policy_version: oss-v2
    differential_threshold: 80
    blocking:
      lint: true
      tests: true
      build: true
      sast_severities: [ERROR]
      dependency_severities: [HIGH, CRITICAL]
      secrets: true
    """)


def _build_catalog_entry(req: ServiceFactoryRequest) -> str:
    return textwrap.dedent(f"""\
    service_name: {req.service_name}
    repository: {req.repository}
    owner: {req.owner}
    cost_center: {req.cost_center}
    project_id: {req.gcp_project}
    region: {req.region}
    environment: {req.environment}
    release_model: candidate-promote-rollback
    quality:
      enabled: true
      profile: {req.quality_profile or req.runtime}
      coverage_threshold: {req.coverage_threshold}
      policy_version: oss-v2
      differential_threshold: 80
    deployment:
      enabled: true
      workflow_file: platform-deploy.yml
      image_name: {req.cloud_run_service_name or req.service_name}
      artifact_repository: cgm-sanplat-repo
      build_context: {req.quality_working_directory}
      health_path: {req.health_path}
    finops:
      service: {req.service_name}
      env: {req.environment}
      owner: {req.owner}
      cost_center: {req.cost_center}
    """)


def _build_platform_deploy_workflow() -> str:
    return (_TEMPLATE_DIR / "platform-deploy.yml").read_text()


def _build_platform_rollback_workflow() -> str:
    rollback_template = _TEMPLATE_DIR / "platform-rollback.yml"
    if rollback_template.exists():
        return rollback_template.read_text()
    return (_REPO_ROOT / ".github" / "workflows" / "platform-rollback.yml").read_text()


def _build_semantic_release_workflow(service_name: str = "") -> str:
    workflow = textwrap.dedent("""\
    name: Semantic Release

    on:
      push:
        branches: [main]

    permissions:
      contents: write
      issues: write
      pull-requests: write

    concurrency:
      group: semantic-release
      cancel-in-progress: false

    jobs:
      release:
        runs-on: ${{{{ (github.ref == 'refs/heads/main' && vars.CGM_ACTIONS_RUNNER == 'cgm-release-local') && 'cgm-release-local' || 'ubuntu-latest' }}}}
        steps:
          - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
            with:
              fetch-depth: 0
          - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
            with:
              node-version: "22"
          - name: Create semantic version tag and GitHub release
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: >-
              npx --yes
              --package semantic-release@25.0.7
              --package @semantic-release/commit-analyzer@13.0.1
              --package @semantic-release/release-notes-generator@14.1.1
              --package @semantic-release/github@12.0.9
              semantic-release
    """)

    gate = f"""      - name: Require exact OSS quality evidence
        uses: diegomad14/gcp-engineering-platform-api/.github/actions/verify-quality@ac9d68554c8b6332013785a5bcf451eabfee93ec
        with:
          platform-api-url: ${{{{ vars.ENG_PLATFORM_API_URL }}}}
          service-name: {service_name}
          commit-sha: ${{{{ github.sha }}}}
          wait-seconds: '1800'
"""
    return workflow.replace(
        "      - name: Create semantic version",
        gate + "      - name: Create semantic version",
    )


def _build_agent_prompt(req: ServiceFactoryRequest) -> str:
    return textwrap.dedent(f"""\
    Implement Engineering Platform adoption for `{req.service_name}` in `{req.repository}`.

    Requirements:
    - Create a branch `chore/adopt-engineering-platform-deploy`.
    - Add generated workflows under `.github/workflows/`.
    - Add the generated quality config and service release contract.
    - Open a PR with a Conventional Commit title.
    - Do not commit secrets, `.env`, service account JSON, tokens, customer data, or wiki-only notes.
    - Validate with actionlint and the repo's normal test/build commands.
    - Configure repository variable `CGM_ACTIONS_RUNNER` as `ubuntu-latest` by
      default; use `cgm-release-local` only from the documented disposable-VM
      GitHub Actions runner contingency.
    - After merge, wait for semantic-release to create a `vX.Y.Z` tag.
    - Deploy only from Engineering Platform `/deployments` by selecting service `{req.service_name}` and the generated tag.

    Never use GCP Console, `gcloud run deploy`, `gcloud run services update-traffic`, `gh workflow run`, or direct GitHub API calls for normal production deploy.
    If GitHub blocks a run, follow `release_process` and the GitHub Actions
    blocked runbook: preserve the same SHA/tag, do not create a parallel tag,
    never run the runner directly on a developer host, and record any approved
    break-glass deployment as `Manual/untracked`.
    """)


def _build_labels_manifest(req: ServiceFactoryRequest) -> str:
    """Generate the Cloud Run labels manifest."""
    return textwrap.dedent(f"""\
    # Cloud Run Service Labels — generated by Engineering Platform Service Factory
    # Apply with:
    #   gcloud run services update {req.service_name} \\
    #     --project={req.gcp_project} \\
    #     --region={req.region} \\
    #     --update-labels=service={req.service_name},env={req.environment},owner={req.owner},cost_center={req.cost_center}

    labels:
      service: {req.service_name}
      env: {req.environment}
      owner: {req.owner}
      cost_center: {req.cost_center}
    """)


def _build_checklist(req: ServiceFactoryRequest) -> list[str]:
    """Generate an onboarding checklist."""
    return [
        f"Confirm Cloud Run service exists: {req.service_name} in {req.gcp_project} ({req.region})",
        f"Apply labels: service={req.service_name}, env={req.environment}, owner={req.owner}, cost_center={req.cost_center}",
        "Confirm Artifact Registry repository exists",
        "Confirm runtime and deployer service accounts exist",
        "Configure WIF/OIDC for the deployer SA (see docs/standards/github-actions-wif.md)",
        "Add QUALITY_API_TOKEN to GitHub organization/repository secrets",
        "Add ENG_PLATFORM_API_URL, GCP_WIF_PROVIDER, GCP_WIF_SERVICE_ACCOUNT, GCP_PROJECT_ID, GCP_REGION to GitHub vars",
        "Add CGM_ACTIONS_RUNNER=ubuntu-latest; reserve cgm-release-local for the documented disposable-VM runner contingency",
        "Confirm the local emergency runner image, QEMU/cloud-localds prerequisites and pinned SHA-256 values are available to operators",
        "Copy generated platform-deploy.yml, platform-rollback.yml, CI/quality, and semantic-release workflows into the service repository",
        "Copy gcp-service-release.yaml to the service repository",
        "Add the generated catalog entry to Engineering Platform API catalog/services/<service>.yaml",
        "Open PRs with generated artifacts and catalog entry",
        "Merge, wait for semantic-release tag, then deploy from Engineering Platform /deployments",
    ]


def get_templates() -> list[ServiceFactoryTemplate]:
    return _KNOWN_TEMPLATES


def generate_plan(req: ServiceFactoryRequest) -> ServiceFactoryPlan:
    contract_yaml = _build_yaml_contract(req)
    service_name = req.service_name

    plan = ServiceFactoryPlan(
        repository=req.repository,
        service_name=service_name,
        generated_files=[
            "gcp-service-release.yaml",
            ".github/workflows/ci.yml",
            ".github/workflows/platform-deploy.yml",
            ".github/workflows/platform-rollback.yml",
            ".github/workflows/semantic-release.yml",
            f"catalog/services/{service_name}.yaml",
            ".quality-gate.yml",
            f"{req.quality_working_directory.rstrip('/')}/.quality-sources.json",
            "cloud-run-service-labels.yaml",
            "onboarding-checklist.md",
            "agent-handoff-prompt.md",
        ],
        checklist=_build_checklist(req),
        yaml_contract=contract_yaml,
        caller_pr_check=_build_caller_workflow(
            f"{req.service_name} PR Check",
            "reusable-pr-check.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_release_candidate=_build_caller_workflow(
            f"{req.service_name} Release Candidate",
            "reusable-cloud-run-release-candidate.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_promote=_build_caller_workflow(
            f"{req.service_name} Promote",
            "reusable-cloud-run-promote.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_rollback=_build_caller_workflow(
            f"{req.service_name} Rollback",
            "reusable-cloud-run-rollback.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        platform_deploy_workflow=_build_platform_deploy_workflow(),
        platform_rollback_workflow=_build_platform_rollback_workflow(),
        semantic_release_workflow=_build_semantic_release_workflow(req.service_name),
        catalog_entry=_build_catalog_entry(req),
        agent_prompt=_build_agent_prompt(req),
        labels_manifest=_build_labels_manifest(req),
        quality_config=_build_quality_config(req),
        quality_sources=json.dumps(
            {
                "roots": ["src"],
                "exclude": ["**/*.test.ts", "**/*.test.tsx", "src/test/*", "**/*.d.ts"]
                if (req.quality_profile or req.runtime) == "node"
                else [],
            },
            indent=2,
        ),
        sonar_properties="",
    )

    return plan
