"""Service Factory — generates onboarding artifacts for new services.

Generates YAML contracts, caller workflow files, and checklists.
Does NOT create GCP resources, IAM bindings, or secrets.
"""

import textwrap
import json
from pathlib import Path

import yaml

from ..models import ServiceFactoryPlan, ServiceFactoryRequest, ServiceFactoryTemplate

_KNOWN_TEMPLATES = [
    ServiceFactoryTemplate(
        name="cloud-run-api",
        description="Cloud Run API service (Python FastAPI)",
        type="api",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-web",
        description="Cloud Run Web service (React/Vite/nginx)",
        type="web",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-worker",
        description="Cloud Run worker service (background processing)",
        type="worker",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-integration",
        description="Cloud Run integration adapter (external API proxy)",
        type="integration",
    ),
]

_REPO_ROOT = Path(__file__).resolve().parents[3]
_SERVICE_FACTORY_TEMPLATE_DIR = _REPO_ROOT / "templates" / "service-factory"


def _build_yaml_contract(req: ServiceFactoryRequest) -> str:
    """Generate a proposal, with HTTP release semantics only for Services."""
    is_job = req.runtime_kind == "cloud_run_job"
    target: dict[str, object] = {
        "platform": "gcp-cloud-run",
        "runtime_kind": req.runtime_kind,
        "service_name": req.service_name,
        "project_id": req.gcp_project,
        "region": req.region,
    }
    if not is_job:
        target.update(
            url=f"https://{req.service_name}-XXXXX-uc.a.run.app",
            health_path=req.health_path,
            openapi_path=req.openapi_path,
            expected_openapi_paths=1,
        )
    contract: dict[str, object] = {
        "service": {
            "name": req.service_name,
            "repository": req.repository,
            "type": req.service_type,
        },
        "release_target": target,
        "quality": {
            "quality_gate": {
                "enabled": True,
                "profile": req.quality_profile or req.runtime,
                "working_directory": req.quality_working_directory,
                "coverage_threshold": req.coverage_threshold,
                "policy_version": "oss-v2",
                "differential_threshold": 80,
                "blocking": True,
            }
        },
        "security": {
            "workload_identity_provider": "${{ vars.GCP_WIF_PROVIDER }}",
            "deployer_service_account": "${{ vars.GCP_WIF_SERVICE_ACCOUNT }}",
            "forbidden": ["GCP_SA_KEY", "service_account_json", ".env"],
        },
        "finops": {"labels": _labels(req)},
    }
    if is_job:
        contract["deployment"] = {
            "enabled": False,
            "executor": "cloud_build",
            "review_required": "Review the Cloud Run Job executor and job-specific release policy before enabling deployment.",
        }
    else:
        contract["validation_targets"] = {
            "smoke_endpoints": [
                {
                    "name": name,
                    "path": "/health",
                    "expected_status": 200,
                    "pii_safe": True,
                    "external_source": True,
                }
                for name in req.validation_targets
                if name.strip()
            ]
        }
    return (
        "# Release contract proposal; no Cloud Run resource has been created.\n"
        f"# Repo: {req.repository}\n" + yaml.safe_dump(contract, sort_keys=False)
    )


def _build_caller_workflow(
    workflow_name: str,
    platform_workflow: str,
    service_name: str,
    service_type: str,
    quality_profile: str,
    quality_working_directory: str,
    coverage_threshold: float,
) -> str:
    """Generate a caller workflow YAML."""
    if platform_workflow == "reusable-pr-check.yml":
        return textwrap.dedent(
            f"""\
        # {workflow_name} — generated by Engineering Platform Service Factory
        name: {workflow_name}

        on:
          pull_request:
            branches: [main]
          push:
            branches: [main]

        permissions:
          contents: read

        jobs:
          quality:
            uses: diegomad14/gcp-engineering-platform-api/.github/workflows/reusable-quality-gate.yml@bac46b1a70c0305470ed1d4c11a18bf07c09ab76
            with:
              service-name: {service_name}
              profile: {quality_profile}
              working-directory: {quality_working_directory}
              coverage-threshold: {coverage_threshold}
              platform-ref: bac46b1a70c0305470ed1d4c11a18bf07c09ab76
              platform-api-url: ${{{{ vars.ENG_PLATFORM_API_URL }}}}
            secrets:
              QUALITY_API_TOKEN: ${{{{ secrets.QUALITY_API_TOKEN }}}}
        """.replace("${{{{", "${{")
        )

    dispatch = "workflow_dispatch:"
    quality_sha_value = "${{ github.sha }}"
    if platform_workflow in {
        "reusable-cloud-run-promote.yml",
        "reusable-cloud-run-rollback.yml",
    }:
        dispatch = textwrap.dedent("""\
        workflow_dispatch:
          inputs:
            quality_commit_sha:
              description: Commit SHA approved by the quality gate
              required: true
              type: string
        """).rstrip()
        quality_sha_value = "${{ inputs.quality_commit_sha }}"
    header = textwrap.dedent(f"""\
    # {workflow_name} — generated by Engineering Platform Service Factory
    # Calls: diegomad14/gcp-engineering-platform-api/.github/workflows/{platform_workflow}

    name: {workflow_name}

    on:
    """)
    body = textwrap.dedent(
        f"""\
    permissions:
      contents: read
      id-token: write

    jobs:
      call:
        uses: diegomad14/gcp-engineering-platform-api/.github/workflows/{platform_workflow}@bac46b1a70c0305470ed1d4c11a18bf07c09ab76
        with:
          project-id: ${{{{ vars.GCP_PROJECT_ID }}}}
          region: ${{{{ vars.GCP_REGION }}}}
          workload-identity-provider: ${{{{ vars.GCP_WIF_PROVIDER }}}}
          deployer-service-account: ${{{{ vars.GCP_WIF_SERVICE_ACCOUNT }}}}
          api-service-name: {service_name}
          platform-api-url: ${{{{ vars.ENG_PLATFORM_API_URL }}}}
          quality-gate-enabled: true
          quality-commit-sha: {quality_sha_value.replace("${{", "${{{{")}
        secrets:
          QUALITY_API_TOKEN: ${{{{ secrets.QUALITY_API_TOKEN }}}}
    """.replace("${{{{", "${{")
    )
    return header + textwrap.indent(dispatch, "  ") + "\n\n" + body


def _build_quality_config(req: ServiceFactoryRequest) -> str:
    """Generate the repository-owned quality gate configuration."""
    return textwrap.dedent(f"""\
    # Open source quality gate — consumed by reusable-quality-gate.yml
    service_name: {req.service_name}
    profile: {req.quality_profile or req.runtime}
    working_directory: {req.quality_working_directory}
    coverage_threshold: {req.coverage_threshold}
    policy_version: oss-v2
    differential_threshold: 80
    blocking:
      lint: true
      tests: true
      build: true
      sast_severities: [ERROR]
      dependency_severities: [HIGH, CRITICAL]
      secrets: true
    """)


def _labels(req: ServiceFactoryRequest) -> dict[str, str]:
    return {
        "service": req.service_name,
        "env": req.environment,
        "owner": req.owner,
        "cost_center": req.cost_center,
    }


def _build_catalog_entry(req: ServiceFactoryRequest) -> str:
    """A registration proposal never grants log access."""
    is_job = req.runtime_kind == "cloud_run_job"
    deployment: dict[str, object] = {
        "enabled": not is_job,
        "runtime_kind": req.runtime_kind,
        "executor": "cloud_build" if is_job else "auto",
        "image_name": req.cloud_run_service_name or req.service_name,
        "artifact_repository": "cgm-sanplat-repo",
        "build_context": req.quality_working_directory,
        "dockerfile_path": (
            "Dockerfile"
            if req.quality_working_directory == "."
            else f"{req.quality_working_directory}/Dockerfile"
        ),
        "health_path": "" if is_job else req.health_path,
    }
    if not is_job:
        deployment["workflow_file"] = "platform-deploy.yml"
    entry = {
        "management_mode": "managed",
        "service_name": req.service_name,
        "repository": req.repository,
        "owner": req.owner,
        "cost_center": req.cost_center,
        "project_id": req.gcp_project,
        "region": req.region,
        "environment": req.environment,
        "release_model": "managed-release" if is_job else "candidate-promote-rollback",
        "release_policy": "oss-v2",
        "quality": {
            "enabled": True,
            "profile": req.quality_profile or req.runtime,
            "coverage_threshold": req.coverage_threshold,
            "policy_version": "oss-v2",
            "differential_threshold": 80,
        },
        "deployment": deployment,
        "logs": {"enabled": False, "allowed_logins": []},
        "finops": _labels(req),
    }
    return yaml.safe_dump(entry, sort_keys=False)


def _build_platform_deploy_workflow() -> str:
    return (_REPO_ROOT / ".github" / "workflows" / "platform-deploy.yml").read_text()


def _build_platform_rollback_workflow() -> str:
    return (_REPO_ROOT / ".github" / "workflows" / "platform-rollback.yml").read_text()


def _build_semantic_release_workflow(service_name: str = "") -> str:
    workflow = textwrap.dedent("""\
    name: Semantic Release

    on:
      push:
        branches: [main]

    permissions:
      contents: write
      issues: write
      pull-requests: write

    concurrency:
      group: semantic-release
      cancel-in-progress: false

    jobs:
      release:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
            with:
              fetch-depth: 0
          - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
            with:
              node-version: "22"
          - name: Create semantic version tag and GitHub release
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: >-
              npx --yes
              --package semantic-release@25.0.7
              --package @semantic-release/commit-analyzer@13.0.1
              --package @semantic-release/release-notes-generator@14.1.1
              --package @semantic-release/github@12.0.9
              semantic-release
    """)

    gate = f"""      - name: Require exact OSS quality evidence
        uses: diegomad14/gcp-engineering-platform-api/.github/actions/verify-quality@ac9d68554c8b6332013785a5bcf451eabfee93ec
        with:
          platform-api-url: ${{{{ vars.ENG_PLATFORM_API_URL }}}}
          service-name: {service_name}
          commit-sha: ${{{{ github.sha }}}}
          wait-seconds: '1800'
"""
    workflow = workflow.replace("${{{{", "${{").replace("}}}}", "}}")
    return workflow.replace(
        "      - name: Create semantic version",
        gate + "      - name: Create semantic version",
    )


def _build_agent_prompt(req: ServiceFactoryRequest) -> str:
    if req.runtime_kind == "cloud_run_job":
        release_instructions = (
            "- This is a Cloud Run Job proposal. Deployment remains disabled.\n"
            "- Review the Cloud Run Job executor, quality evidence and job-specific release policy before enabling deployment.\n"
            "- Do not install Service deploy/promote/rollback workflows or HTTP health checks for this Job.\n"
        )
    else:
        release_instructions = (
            "- After review and merge, wait for semantic-release to create a vX.Y.Z tag.\n"
            f"- Use the reviewed platform release process for {req.service_name}; preserve the same SHA/tag.\n"
        )
    return (
        f"Prepare Engineering Platform adoption for {req.service_name} in {req.repository}.\n\n"
        "These are local proposals, not evidence of a created or deployed resource.\n"
        "- Review generated artifacts before preparing a PR.\n"
        "- Validate with actionlint and the repository's normal test/build commands.\n"
        "- Preserve protected checks, existing deployment authorization and triggers.\n"
        "- Do not commit secrets, .env, service account JSON, tokens, or customer data.\n"
        f"- From the API repository, validate with: python scripts/catalog_registry.py --check catalog/services/{req.service_name}.yaml\n"
        "- Only after review, rerun with --write to update the runtime JSON catalog.\n"
        "- Registration keeps logs disabled and the reader list empty; a separate reviewed policy change is required for access.\n"
        + release_instructions
        + "Never use GCP Console, gcloud run deploy, gcloud run jobs deploy, traffic updates, or direct workflow dispatch for an unapproved production change.\n"
    )


def _build_labels_manifest(req: ServiceFactoryRequest) -> str:
    """Describe desired labels without applying changes to either resource kind."""
    return (
        f"# {req.runtime_kind} label proposal; review before applying.\n"
        "# No Cloud Run resources, IAM or labels have been changed.\n"
        + yaml.safe_dump({"labels": _labels(req)}, sort_keys=False)
    )


def _build_checklist(req: ServiceFactoryRequest) -> list[str]:
    """Close the proposal-to-runtime-catalog gap explicitly."""
    kind = "Job" if req.runtime_kind == "cloud_run_job" else "Service"
    steps = [
        f"Confirm Cloud Run {kind} identity and existence separately: {req.service_name} in {req.gcp_project} ({req.region}); this plan created no resource",
        "Reserve service_name globally: duplicates across projects, regions or runtime kinds are rejected",
        "Review owner, repository, project_id, region, runtime_kind, quality policy and proposed labels",
        "Confirm Artifact Registry, runtime accounts and deployment authorization through the approved platform process",
        "Review generated CI/quality and semantic-release proposals before copying them to the resource repository",
        f"Review {'gcp-job-release.yaml' if kind == 'Job' else 'gcp-service-release.yaml'}; it does not register or create a resource",
        f"From the API repository run: python scripts/catalog_registry.py --check catalog/services/{req.service_name}.yaml",
        f"After review run: python scripts/catalog_registry.py --write catalog/services/{req.service_name}.yaml",
        "Review the diff of src/eng_platform_api/static_examples/mock_catalog.json, the actual shared source; catalog/services/*.yaml is not loaded at runtime",
        "Verify the new resource in /api/catalog/services after the reviewed catalog is delivered through the normal release process",
        "Keep logs.enabled=false and logs.allowed_logins=[]; approve any log readers in a separate catalog policy review",
    ]
    if kind == "Job":
        steps.append(
            "Keep deployment.enabled=false until the Cloud Run Job executor and job-specific release policy have been reviewed; no Service deploy/promote/rollback workflows or HTTP contract are generated"
        )
    else:
        steps.append(
            "Review proposed platform-deploy.yml and platform-rollback.yml; after approved adoption use the platform release process with the exact qualified SHA/tag"
        )
    return steps


def get_templates() -> list[ServiceFactoryTemplate]:
    return _KNOWN_TEMPLATES


def generate_plan(req: ServiceFactoryRequest) -> ServiceFactoryPlan:
    from . import log_catalog
    from fastapi import HTTPException

    # A draft must not silently turn a known inventory-only resource into a
    # deployment target. Its adoption requires a separately reviewed metadata change.
    existing = next(
        (
            item
            for item in log_catalog.load_catalog()
            if item["service_name"] == req.service_name
        ),
        None,
    )
    if existing and existing.get("management_mode") == "observability_only":
        raise HTTPException(
            status_code=409,
            detail="Observation-only resource cannot use managed operations",
        )
    contract_yaml = _build_yaml_contract(req)
    service_name = req.service_name
    is_job = req.runtime_kind == "cloud_run_job"

    plan = ServiceFactoryPlan(
        repository=req.repository,
        service_name=service_name,
        generated_files=[
            "gcp-job-release.yaml" if is_job else "gcp-service-release.yaml",
            ".github/workflows/ci.yml",
            *(
                []
                if is_job
                else [
                    ".github/workflows/platform-deploy.yml",
                    ".github/workflows/platform-rollback.yml",
                ]
            ),
            ".github/workflows/semantic-release.yml",
            f"catalog/services/{service_name}.yaml",
            ".quality-gate.yml",
            f"{req.quality_working_directory.rstrip('/')}/.quality-sources.json",
            "cloud-run-job-labels.yaml" if is_job else "cloud-run-service-labels.yaml",
            "onboarding-checklist.md",
            "agent-handoff-prompt.md",
        ],
        checklist=_build_checklist(req),
        yaml_contract=contract_yaml,
        caller_pr_check=_build_caller_workflow(
            f"{req.service_name} PR Check",
            "reusable-pr-check.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_release_candidate=""
        if is_job
        else _build_caller_workflow(
            f"{req.service_name} Release Candidate",
            "reusable-cloud-run-release-candidate.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_promote=""
        if is_job
        else _build_caller_workflow(
            f"{req.service_name} Promote",
            "reusable-cloud-run-promote.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_rollback=""
        if is_job
        else _build_caller_workflow(
            f"{req.service_name} Rollback",
            "reusable-cloud-run-rollback.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        platform_deploy_workflow="" if is_job else _build_platform_deploy_workflow(),
        platform_rollback_workflow=""
        if is_job
        else _build_platform_rollback_workflow(),
        semantic_release_workflow=_build_semantic_release_workflow(req.service_name),
        catalog_entry=_build_catalog_entry(req),
        agent_prompt=_build_agent_prompt(req),
        labels_manifest=_build_labels_manifest(req),
        quality_config=_build_quality_config(req),
        quality_sources=json.dumps(
            {
                "roots": ["src"],
                "exclude": ["**/*.test.ts", "**/*.test.tsx", "src/test/*", "**/*.d.ts"]
                if (req.quality_profile or req.runtime) == "node"
                else [],
            },
            indent=2,
        ),
        sonar_properties="",
    )

    return plan
