"""Service Factory — generates onboarding artifacts for new services.

Generates YAML contracts, caller workflow files, and checklists.
Does NOT create GCP resources, IAM bindings, or secrets.
"""

import textwrap

from ..models import ServiceFactoryPlan, ServiceFactoryRequest, ServiceFactoryTemplate

_KNOWN_TEMPLATES = [
    ServiceFactoryTemplate(
        name="cloud-run-api",
        description="Cloud Run API service (Python FastAPI)",
        type="api",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-web",
        description="Cloud Run Web service (React/Vite/nginx)",
        type="web",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-worker",
        description="Cloud Run worker service (background processing)",
        type="worker",
    ),
    ServiceFactoryTemplate(
        name="cloud-run-integration",
        description="Cloud Run integration adapter (external API proxy)",
        type="integration",
    ),
]


def _build_yaml_contract(req: ServiceFactoryRequest) -> str:
    """Generate the gcp-service-release.yaml contract."""
    return textwrap.dedent(
        f"""\
    # Service release contract — generated by Engineering Platform Service Factory
    # Repo: diegomad14/gcp-engineering-platform-api

    service:
      name: {req.service_name}
      repository: {req.repository}
      type: {req.service_type}

    release_target:
      platform: gcp-cloud-run
      service_name: {req.service_name}
      project_id: {req.gcp_project}
      region: {req.region}
      url: https://{req.service_name}-XXXXX-uc.a.run.app
      health_path: {req.health_path}
      openapi_path: {req.openapi_path}
      expected_openapi_paths: 1

    validation_targets:
      smoke_endpoints:{_format_validation_targets(req.validation_targets)}

    quality:
      quality_gate:
        enabled: true
        profile: {req.quality_profile or req.runtime}
        working_directory: {req.quality_working_directory}
        coverage_threshold: {req.coverage_threshold}
        blocking: true

    security:
      workload_identity_provider: ${{{{ vars.GCP_WIF_PROVIDER }}}}
      deployer_service_account: ${{{{ vars.GCP_WIF_SERVICE_ACCOUNT }}}}
      forbidden:
        - GCP_SA_KEY
        - service_account_json
        - .env

    finops:
      labels:
        service: {req.service_name}
        env: {req.environment}
        owner: {req.owner}
        cost_center: {req.cost_center}
    """.replace("${{{{", "${{")
    )


def _format_validation_targets(targets: list[str]) -> str:
    if not targets:
        return " []"
    lines = []
    for t in targets:
        lines.append(f"      - name: {t}")
        lines.append("        path: /health")
        lines.append("        expected_status: 200")
        lines.append("        pii_safe: true")
        lines.append("        external_source: true")
    return "\n" + "\n".join(lines)


def _build_caller_workflow(
    workflow_name: str,
    platform_workflow: str,
    service_name: str,
    service_type: str,
    quality_profile: str,
    quality_working_directory: str,
    coverage_threshold: float,
) -> str:
    """Generate a caller workflow YAML."""
    if platform_workflow == "reusable-pr-check.yml":
        return textwrap.dedent(
            f"""\
        # {workflow_name} — generated by Engineering Platform Service Factory
        name: {workflow_name}

        on:
          pull_request:
            branches: [main]
          push:
            branches: [main]

        permissions:
          contents: read

        jobs:
          quality:
            uses: diegomad14/gcp-engineering-platform-api/.github/workflows/reusable-quality-gate.yml@v1
            with:
              service-name: {service_name}
              profile: {quality_profile}
              working-directory: {quality_working_directory}
              coverage-threshold: {coverage_threshold}
              platform-api-url: ${{{{ vars.ENG_PLATFORM_API_URL }}}}
            secrets:
              QUALITY_API_TOKEN: ${{{{ secrets.QUALITY_API_TOKEN }}}}
        """.replace("${{{{", "${{")
        )

    dispatch = "workflow_dispatch:"
    quality_sha_value = "${{ github.sha }}"
    if platform_workflow in {
        "reusable-cloud-run-promote.yml",
        "reusable-cloud-run-rollback.yml",
    }:
        dispatch = textwrap.dedent("""\
        workflow_dispatch:
          inputs:
            quality_commit_sha:
              description: Commit SHA approved by the quality gate
              required: true
              type: string
        """).rstrip()
        quality_sha_value = "${{ inputs.quality_commit_sha }}"
    header = textwrap.dedent(f"""\
    # {workflow_name} — generated by Engineering Platform Service Factory
    # Calls: diegomad14/gcp-engineering-platform-api/.github/workflows/{platform_workflow}

    name: {workflow_name}

    on:
    """)
    body = textwrap.dedent(
        f"""\
    permissions:
      contents: read
      id-token: write

    jobs:
      call:
        uses: diegomad14/gcp-engineering-platform-api/.github/workflows/{platform_workflow}@v1
        with:
          project-id: ${{{{ vars.GCP_PROJECT_ID }}}}
          region: ${{{{ vars.GCP_REGION }}}}
          workload-identity-provider: ${{{{ vars.GCP_WIF_PROVIDER }}}}
          deployer-service-account: ${{{{ vars.GCP_WIF_SERVICE_ACCOUNT }}}}
          api-service-name: {service_name}
          platform-api-url: ${{{{ vars.ENG_PLATFORM_API_URL }}}}
          quality-gate-enabled: true
          quality-commit-sha: {quality_sha_value.replace("${{", "${{{{")}
        secrets:
          QUALITY_API_TOKEN: ${{{{ secrets.QUALITY_API_TOKEN }}}}
    """.replace("${{{{", "${{")
    )
    return header + textwrap.indent(dispatch, "  ") + "\n\n" + body


def _build_quality_config(req: ServiceFactoryRequest) -> str:
    """Generate the repository-owned quality gate configuration."""
    return textwrap.dedent(f"""\
    # Open source quality gate — consumed by reusable-quality-gate.yml
    service_name: {req.service_name}
    profile: {req.quality_profile or req.runtime}
    working_directory: {req.quality_working_directory}
    coverage_threshold: {req.coverage_threshold}
    blocking:
      lint: true
      tests: true
      build: true
      sast_severities: [ERROR]
      dependency_severities: [HIGH, CRITICAL]
      secrets: true
    """)


def _build_labels_manifest(req: ServiceFactoryRequest) -> str:
    """Generate the Cloud Run labels manifest."""
    return textwrap.dedent(f"""\
    # Cloud Run Service Labels — generated by Engineering Platform Service Factory
    # Apply with:
    #   gcloud run services update {req.service_name} \\
    #     --project={req.gcp_project} \\
    #     --region={req.region} \\
    #     --update-labels=service={req.service_name},env={req.environment},owner={req.owner},cost_center={req.cost_center}

    labels:
      service: {req.service_name}
      env: {req.environment}
      owner: {req.owner}
      cost_center: {req.cost_center}
    """)


def _build_checklist(req: ServiceFactoryRequest) -> list[str]:
    """Generate an onboarding checklist."""
    return [
        f"Create GCP Cloud Run service: {req.service_name} in {req.gcp_project} ({req.region})",
        f"Apply labels: service={req.service_name}, env={req.environment}, owner={req.owner}, cost_center={req.cost_center}",
        "Create Artifact Registry repository (if not exists)",
        f"Create runtime service account: {req.service_name}-runtime@{req.gcp_project}.iam.gserviceaccount.com",
        f"Create deployer service account: {req.service_name}-deployer@{req.gcp_project}.iam.gserviceaccount.com",
        "Configure WIF/OIDC for deployer SA (see docs/standards/github-actions-wif.md)",
        "Add QUALITY_API_TOKEN to GitHub organization/repository secrets",
        "Add ENG_PLATFORM_API_URL, GCP_WIF_PROVIDER, GCP_WIF_SERVICE_ACCOUNT, GCP_PROJECT_ID, GCP_REGION to GitHub vars",
        "Copy generated caller workflows to .github/workflows/ in the service repository",
        "Copy gcp-service-release.yaml to the service repository",
        "Open PR with generated artifacts",
        "Complete platform adoption readiness checklist",
        "Schedule platform review",
    ]


def get_templates() -> list[ServiceFactoryTemplate]:
    return _KNOWN_TEMPLATES


def generate_plan(req: ServiceFactoryRequest) -> ServiceFactoryPlan:
    contract_yaml = _build_yaml_contract(req)
    service_name = req.service_name

    plan = ServiceFactoryPlan(
        repository=req.repository,
        service_name=service_name,
        generated_files=[
            "gcp-service-release.yaml",
            "caller-pr-check.yml",
            "caller-release-candidate.yml",
            "caller-promote.yml",
            "caller-rollback.yml",
            ".quality-gate.yml",
            "cloud-run-service-labels.yaml",
            "onboarding-checklist.md",
        ],
        checklist=_build_checklist(req),
        yaml_contract=contract_yaml,
        caller_pr_check=_build_caller_workflow(
            f"{req.service_name} PR Check",
            "reusable-pr-check.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_release_candidate=_build_caller_workflow(
            f"{req.service_name} Release Candidate",
            "reusable-cloud-run-release-candidate.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_promote=_build_caller_workflow(
            f"{req.service_name} Promote",
            "reusable-cloud-run-promote.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        caller_rollback=_build_caller_workflow(
            f"{req.service_name} Rollback",
            "reusable-cloud-run-rollback.yml",
            service_name,
            req.service_type,
            req.quality_profile or req.runtime,
            req.quality_working_directory,
            req.coverage_threshold,
        ),
        labels_manifest=_build_labels_manifest(req),
        quality_config=_build_quality_config(req),
        sonar_properties="",
    )

    return plan
