name: Quality Gate

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    uses: diegomad14/gcp-engineering-platform-api/.github/workflows/reusable-quality-gate.yml@bac46b1a70c0305470ed1d4c11a18bf07c09ab76
    with:
      service-name: SERVICE_NAME_HERE
      profile: python
      working-directory: .
      coverage-threshold: 70
      platform-ref: bac46b1a70c0305470ed1d4c11a18bf07c09ab76
      platform-api-url: ${{ vars.ENG_PLATFORM_API_URL }}
    secrets:
      QUALITY_API_TOKEN: ${{ secrets.QUALITY_API_TOKEN }}
