name: Quality Gate

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    uses: diegomad14/gcp-engineering-platform-api/.github/workflows/reusable-quality-gate.yml@ac9d68554c8b6332013785a5bcf451eabfee93ec
    with:
      service-name: SERVICE_NAME_HERE
      profile: python
      working-directory: .
      coverage-threshold: 70
      platform-ref: ac9d68554c8b6332013785a5bcf451eabfee93ec
      platform-api-url: ${{ vars.ENG_PLATFORM_API_URL }}
    secrets:
      QUALITY_API_TOKEN: ${{ secrets.QUALITY_API_TOKEN }}
