# Cloud Run Service Labels — generated by Engineering Platform Service Factory
# Apply with:
#   gcloud run services update {{SERVICE_NAME}} \
#     --project={{GCP_PROJECT}} \
#     --region={{REGION}} \
#     --update-labels=service={{SERVICE_NAME}},env={{ENV}},owner={{OWNER}},cost_center={{COST_CENTER}}

labels:
  service: {{SERVICE_NAME}}
  env: {{ENV}}
  owner: {{OWNER}}
  cost_center: {{COST_CENTER}}
