# Service release contract — generated by Engineering Platform Service Factory

service:
  name: {{SERVICE_NAME}}
  repository: {{REPOSITORY}}
  type: {{SERVICE_TYPE}}

release_target:
  platform: gcp-cloud-run
  service_name: {{SERVICE_NAME}}
  project_id: {{GCP_PROJECT}}
  region: {{REGION}}
  url: https://{{SERVICE_NAME}}-XXXXX-uc.a.run.app
  health_path: {{HEALTH_PATH}}
  openapi_path: {{OPENAPI_PATH}}
  expected_openapi_paths: 1

validation_targets:
  smoke_endpoints:
{{VALIDATION_TARGETS}}

quality:
  quality_gate:
    enabled: true
    profile: {{QUALITY_PROFILE}}
    working_directory: {{QUALITY_WORKING_DIRECTORY}}
    coverage_threshold: 70
    blocking: true

security:
  workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
  deployer_service_account: ${{ vars.GCP_WIF_SERVICE_ACCOUNT }}
  forbidden:
    - GCP_SA_KEY
    - service_account_json
    - .env

finops:
  labels:
    service: {{SERVICE_NAME}}
    env: {{ENVIRONMENT}}
    owner: {{OWNER}}
    cost_center: {{COST_CENTER}}
