# Local-first release contract — generated by Engineering Platform Service Factory
schema_version: 1

service:
  name: __SERVICE_NAME__
  repository: __REPOSITORY__
  profile: __PROFILE__
  working_directory: __WORKING_DIRECTORY__

deployment:
  platform: gcp-cloud-run
  project_id: __PROJECT_ID__
  region: __REGION__
  image_name: __IMAGE_NAME__
  artifact_repository: __ARTIFACT_REPOSITORY__
  health_path: __HEALTH_PATH__
  build_platform: linux/amd64

quality:
  policy_id: oss-v2
  differential_coverage_minimum: 80
  evidence_ttl_hours: 168
  exact_commit_and_base_required: true

execution:
  publisher: gh
  single_publisher: true
  actions_dispatch: false
  cloud_build: false
  remote_effects_require_confirmation: true
  preserve_github_deployments: true
  preserve_sanplat_release_group_id: true

# This file is declarative. It does not grant IAM, change branch protection,
# disable Actions, or authorize a production release.
